import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="fixed top-0 left-0 w-full flex gap-4 p-4 bg-zinc-50 dark:bg-zinc-900 border-b border-black/[.08] dark:border-white/[.145]">
          <Link href="/">홈</Link>
          <Link href="/about">about</Link>
          <Link href="/course">course</Link>
        </nav>
        <div className="pt-16">{children}</div>
      </body>
    </html>
  );
}
